### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: bokeh.html for GET /api/graph

### ISSUE THREAD

**Issue by SimonSchubert** [StanGirard/SEOToolkit#3]
I'm running the latest master without any modification. 

Log:
06/19/2020 01:15:58 PM - INFO - 127.0.0.1 - - [19/Jun/2020 13:15:58] "GET /api/graph?url=https://linuxcommandlibrary.com/tips.html HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/simon/projects/SEOToolkit/flask_api.py", line 115, in interactive_graph
    return generate_interactive_graph(conn, urls, relaunch, maxi_urls)
  File "/Users/simon/projects/SEOToolkit/flask_api.py", line 103, in generate_interactive_graph
    return update_or_insert_graph_in_db(conn, urls, maximum_urls)
  File "/Users/simon/projects/SEOToolkit/flask_api.py", line 52, in update_or_insert_graph_in_db
    return render_template("bokeh.html", script=script, div=div, domain=domain, template="Flask", time=datetime.now().strftime("%m/%d/%Y, %H:%M:%S"))
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bokeh.html

**Comment by StanGirard** [comment]
I just fixed it :) Sorry about it.

**Comment by SimonSchubert** [comment]
Thanks a lot. I still got the `jinja2.exceptions.TemplateNotFound: bokeh.html` error and I had to copy the bokeh.html from `toolkit/template/` to `templates`. But maybe it was a caching issue, idk. Now it works. 

`api/analysis/keywords` also works fine now

Thanks a lot again. I'm new to the seo business. The project looks promising.
