### ISSUE TITLE
/api/extract/images gives 500 Internal Server Error

### ISSUE THREAD

**Issue by SimonSchubert** [StanGirard/SEOToolkit#5]
I like the direction in which the project is going. Thanks for adding new endpoints. For some urls the call works fine but for the following it crashed:

Log
06/20/2020 01:47:31 PM - INFO - 127.0.0.1 - - [20/Jun/2020 13:47:31] "GET /api/extract/images?url=https://linuxcommandlibrary.com/basics.html HTTP/1.1" 500 -
06/20/2020 01:47:31 PM - INFO - 127.0.0.1 - - [20/Jun/2020 13:47:31] "GET /favicon.ico HTTP/1.1" 404 -
06/20/2020 01:47:37 PM - DEBUG - Starting new HTTPS connection (1): linuxcommandlibrary.com:443
06/20/2020 01:47:37 PM - DEBUG - https://linuxcommandlibrary.com:443 "GET /basics.html HTTP/1.1" 200 None
06/20/2020 01:47:37 PM - ERROR - Exception on /api/extract/images [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_api.py", line 123, in find_all_images_page
    return find_all_images(value)
  File "/Users/simon/projects/SEOToolkit/toolkit/seo/images.py", line 13, in find_all_images
    alt = image['alt']
  File "/usr/local/lib/python3.7/site-packages/bs4/element.py", line 1401, in __getitem__
    return self.attrs[key]
KeyError: 'alt'

**Comment by StanGirard** [comment]
Yeah I expected this result. I was about to fix it. Didn't expect you to be so quick about it :) 

It is a quickfix however. It crashes when no alt has been set on the picture. 
Should be done in a couple of minutes

**Comment by StanGirard** [comment]
Done! Thanks for your help with finding bugs.

Please feel free to tell me about any features you would like to see.

I've open an issue for feature requests or code improvement.
